---
- name: "Get IP Address from Orion"
  connection: local
  gather_facts: false
  hosts: localhost
  vars_promp:
    - name: subnet
      private: no
    - name: orion_server
      private: no
    - name: orion_username
      private: no
    - name: orion_password
  tasks:
    # - name: "Install pip"
    #   easy_install:
    #     name: pip
    #     state: present
    #   become: yes
    # - name: "Install orionsdk"
    #   pip:
    #     name: orionsdk
    #   become: yes
    - name: "Get IP"
      orion_ipam_record:
        subnet: "{{ subnet }}"
        orion_server: "{{ orion_server }}"
        orion_username: "{{ orion_username }}"
        orion_password: "{{ orion_password }}"
      register: orion_ipam_result
    - name: "Print IP"
      debug:
        msg: "{{ orion_ipam_result.ip_address }}"
