---
namespace: "kalenpeterson_orion_sdk"
name: "orion_ipam_record"
version: "1.0.2"
readme: "README.md"
authors:
    - "Kalen Peterson"
license:
    - " GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)"
tags:
    - orion
    - collection
    - record
repository: "https://github.com/kalenpeterson/ansible-orion"